
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # 映射本地 6379 端口到容器内
    volumes:
      - redis_data:/data # 持久化 Redis 数据
    command: ["redis-server", "--appendonly", "yes"] # 开启持久化（AOF 模式）

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=infoverify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  redis_data:
  pg_data:
